# Generated by Django 4.0.2 on 2022-05-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_avatar_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='firstName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lastName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
