# Generated by Django 4.0.2 on 2022-03-20 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_pledge_supporter_alter_project_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PledgeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='primary_image',
        ),
        migrations.AddField(
            model_name='project',
            name='blurb',
            field=models.TextField(default='short summary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='goal_date',
            field=models.DateTimeField(default='2022-10-20T14:28:23.382748Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='secondary_image',
            field=models.URLField(default='https://via.placeholder.com/300.jpg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pledge',
            name='pledge_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='pledge_type', to='projects.pledgetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='projects.category'),
            preserve_default=False,
        ),
      
    ]
