# Generated by Django 4.0.2 on 2022-03-22 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_category_pledgetype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='pledge_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='projects.project'),
        ),
        migrations.AddField(
            model_name='pledgetype',
            name='pledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pledge_type', to='projects.pledge'),
        ),
    ]
