# Generated by Django 4.0.2 on 2022-03-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_category_project_remove_pledgetype_pledge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='open', max_length=200),
            preserve_default=False,
        ),
    ]
