# Generated by Django 4.0.2 on 2022-03-22 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='pledge_type',
            field=models.ForeignKey(default='exit', on_delete=django.db.models.deletion.CASCADE, related_name='pledge_id', to='projects.pledgetype'),
            preserve_default=False,
        ),
    ]
