# Generated by Django 4.0.2 on 2022-03-26 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_pledge_pledge_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='pledge_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pledge_id', to='projects.pledgetype'),
        ),
    ]
