# Generated by Django 4.0.2 on 2022-05-04 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='pledge_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='progress',
        ),
        migrations.AddField(
            model_name='project',
            name='pledge_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pledge_id', to='projects.pledgetype'),
        ),
    ]
