# Generated by Django 4.0.2 on 2022-05-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_project_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='goal_date',
            field=models.DateTimeField(),
        ),
    ]
