# Generated by Django 4.0.2 on 2022-05-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_project_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
