# Generated by Django 4.0.2 on 2022-05-07 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_remove_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='secondary_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
